/*
Programmer: Tayyaab Tanveer
 * Date: March 31 2018
 * Program Name: Matching Game
 * Program Description: This program uses arrays to simulate a matching game.
 * A grid of cards will be displayed and the user is to select 2 cards at a time
 * looking for the matching cards. The goal of this game is to see how quickly the user can find all the matches
 */
/*
 * MemoryUI.java
 *
 * Created on 31-Mar-2018, 7:20:28 PM
 */

/**
 *
 * @author Desktop
 */
import java.util.*;


import javax.swing.Timer;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JLabel;

public class MemoryUI extends javax.swing.JFrame {

    ArrayList<String> cards = new ArrayList();
    ArrayList<String> set = new ArrayList();
    ImageIcon a = new ImageIcon("JAK.png");
    ImageIcon b = new ImageIcon("ARROW.jpg");
    ImageIcon c = new ImageIcon("STRAFE.png");
    ImageIcon d = new ImageIcon("POT.png");
    ImageIcon e = new ImageIcon("CLAW.png");
    ImageIcon f = new ImageIcon("MUTE.png");
    ImageIcon g = new ImageIcon("CRYSTAK.png");
    ImageIcon h = new ImageIcon("RAP.png");
    ImageIcon back = new ImageIcon("LOGO.png");
    ImageIcon done = new ImageIcon("DONE.png");
    int count, c1, c2, card1, card2, click1, click2, click3, click4, click5, click6, click7, click8, click9, click10, click11, click12, click13, click14, click15, click16;
    int tries;
    int cardsLeft = 16;
    int[] change = new int[16];

    /** Creates new form MemoryUI */
    public MemoryUI() {
        initComponents();
        winGif.setVisible(false);

    }

    //timer.stop()
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        Rules = new javax.swing.JOptionPane();
        winGif = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        card1Button = new javax.swing.JButton();
        card2Button = new javax.swing.JButton();
        card3Button = new javax.swing.JButton();
        card4Button = new javax.swing.JButton();
        card5Button = new javax.swing.JButton();
        card6Button = new javax.swing.JButton();
        card7Button = new javax.swing.JButton();
        card8Button = new javax.swing.JButton();
        card9Button = new javax.swing.JButton();
        card10Button = new javax.swing.JButton();
        card11Button = new javax.swing.JButton();
        card12Button = new javax.swing.JButton();
        card13Button = new javax.swing.JButton();
        card14Button = new javax.swing.JButton();
        card15Button = new javax.swing.JButton();
        card16Button = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        againButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        backgroundLogo = new javax.swing.JLabel();

        jOptionPane1.setBackground(new java.awt.Color(204, 255, 51));

        Rules.setBackground(new java.awt.Color(255, 204, 204));
        Rules.setAlignmentX(5.0F);
        Rules.setAlignmentY(5.0F);
        Rules.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Rules.setFont(new java.awt.Font("Comic Sans MS", 0, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 702, 683));
        setMinimumSize(new java.awt.Dimension(705, 620));
        getContentPane().setLayout(null);

        winGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giphy.gif"))); // NOI18N
        getContentPane().add(winGif);
        winGif.setBounds(90, 200, 500, 226);

        mainTitle.setFont(new java.awt.Font("Calibri", 1, 36));
        mainTitle.setForeground(new java.awt.Color(0, 204, 204));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainTitle.setText("Matching Game!");
        getContentPane().add(mainTitle);
        mainTitle.setBounds(210, 20, 248, 44);

        card1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card1ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card1Button);
        card1Button.setBounds(10, 80, 107, 83);

        card2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card2ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card2Button);
        card2Button.setBounds(200, 80, 107, 83);

        card3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card3ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card3Button);
        card3Button.setBounds(380, 80, 107, 83);

        card4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card4ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card4Button);
        card4Button.setBounds(570, 80, 107, 83);

        card5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card5ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card5Button);
        card5Button.setBounds(570, 180, 107, 83);

        card6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card6ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card6Button);
        card6Button.setBounds(380, 180, 107, 83);

        card7Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card7ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card7Button);
        card7Button.setBounds(200, 180, 107, 83);

        card8Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card8Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card8ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card8Button);
        card8Button.setBounds(10, 180, 107, 83);

        card9Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card9Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card9ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card9Button);
        card9Button.setBounds(570, 280, 107, 83);

        card10Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card10Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card10ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card10Button);
        card10Button.setBounds(380, 280, 107, 83);

        card11Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card11Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card11ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card11Button);
        card11Button.setBounds(200, 280, 107, 83);

        card12Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card12Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card12ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card12Button);
        card12Button.setBounds(10, 280, 107, 83);

        card13Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card13Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card13ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card13Button);
        card13Button.setBounds(570, 380, 107, 83);

        card14Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card14Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card14ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card14Button);
        card14Button.setBounds(380, 380, 107, 83);

        card15Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card15Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card15ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card15Button);
        card15Button.setBounds(200, 380, 107, 83);

        card16Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        card16Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card16ButtonMouseClicked(evt);
            }
        });
        getContentPane().add(card16Button);
        card16Button.setBounds(10, 380, 107, 83);

        playButton.setBackground(new java.awt.Color(102, 0, 102));
        playButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("Play!");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(60, 500, 71, 58);

        againButton.setBackground(new java.awt.Color(255, 102, 0));
        againButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        againButton.setForeground(new java.awt.Color(255, 255, 255));
        againButton.setText("Guess Again");
        againButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againButtonActionPerformed(evt);
            }
        });
        getContentPane().add(againButton);
        againButton.setBounds(220, 500, 170, 58);

        exitButton.setBackground(new java.awt.Color(0, 102, 102));
        exitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 102));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(490, 500, 107, 58);

        backgroundLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoback.jpg"))); // NOI18N
        backgroundLogo.setMaximumSize(new java.awt.Dimension(750, 750));
        backgroundLogo.setPreferredSize(new java.awt.Dimension(702, 582));
        getContentPane().add(backgroundLogo);
        backgroundLogo.setBounds(0, -10, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // exit
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        winGif.setVisible(false);

        card16Button.setIcon(back);
        card15Button.setIcon(back);
        card14Button.setIcon(back);
        card13Button.setIcon(back);
        card12Button.setIcon(back);
        card11Button.setIcon(back);
        card10Button.setIcon(back);
        card9Button.setIcon(back);
        card8Button.setIcon(back);
        card7Button.setIcon(back);
        card6Button.setIcon(back);
        card5Button.setIcon(back);
        card4Button.setIcon(back);

        card3Button.setIcon(back);
        card2Button.setIcon(back);

        card1Button.setIcon(back);



        JOptionPane.showMessageDialog(null, "WELCOME" + "\n" + "HOW TO PLAY THIS GAME:" + "\n" + "1. Click on two cards at a time to flip them over." + "\n" + "2. Press Guess Again and the game will see if you have a match!" + "\n" + "3. Matched cards will be flipped to a black logo." + "\n" + "A prompt will pop up when you successfully match all pairs! :)");


        // set change array
        for (int z = 0; z <= 15; z++) {
            change[z] = 1;
        }

        String temp;
        for (int x = 0; x <= 7; x++) {
            for (int y = 1; y <= 2; y++) {
                temp = Integer.toString(x);
                set.add(temp);
            }
        }
        for (int x = 0; x <= 15; x++) {
            double index = Math.floor(Math.random() * (16 - x));
            int index1 = (int) index;
            cards.add(set.get(index1));
            set.remove(set.get(index1));
        }

    }//GEN-LAST:event_playButtonActionPerformed

    private void card1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card1ButtonMouseClicked
        String temp = cards.get(0);

        String desc1 = ((ImageIcon)card1Button.getIcon()).getDescription();
        click1++;
        if (    !desc1.equals("DONE.png")){
count++;
        }

if ((    !desc1.equals("DONE.png")) && (click1 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card1Button.setIcon(a);
        } else if (temp.equals("1")) {
            card1Button.setIcon(b);
        } else if (temp.equals("2")) {
            card1Button.setIcon(c);
        } else if (temp.equals("3")) {
            card1Button.setIcon(d);
        } else if (temp.equals("4")) {
            card1Button.setIcon(e);
        } else if (temp.equals("5")) {
            card1Button.setIcon(f);
        } else if (temp.equals("6")) {
            card1Button.setIcon(g);
        } else if (temp.equals("7")) {
            card1Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[0] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[0] = 0;
//        } else if (count > 2) {
//            card1Button.setIcon(back);
        }}

        // TODO add your handling code here:
    }//GEN-LAST:event_card1ButtonMouseClicked

    private void card2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card2ButtonMouseClicked
        String temp = cards.get(1);
        String desc2 = ((ImageIcon)card2Button.getIcon()).getDescription();
        click2++;
                if (    !desc2.equals("DONE.png")){
count++;
        }

       

if ((    !desc2.equals("DONE.png")) && (click2 == 1) && (count <=2) ) {




//        if ((count <=2) && (card2Button.getIcon().toString != "DONE.png!" ))
        if (temp.equals("0")) {
            card2Button.setIcon(a);
        } else if (temp.equals("1")) {
            card2Button.setIcon(b);
        } else if (temp.equals("2")) {
            card2Button.setIcon(c);
        } else if (temp.equals("3")) {
            card2Button.setIcon(d);
        } else if (temp.equals("4")) {
            card2Button.setIcon(e);
        } else if (temp.equals("5")) {
            card2Button.setIcon(f);
        } else if (temp.equals("6")) {
            card2Button.setIcon(g);
        } else if (temp.equals("7")) {
            card2Button.setIcon(h);
        }

       
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[1] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[1] = 0;
//        } else if (count > 2) {
//            card2Button.setIcon(back);
        }
        }

    }//GEN-LAST:event_card2ButtonMouseClicked

    private void card3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card3ButtonMouseClicked
        String temp = cards.get(2);
        String desc3 = ((ImageIcon)card3Button.getIcon()).getDescription();
        click3++;

                if (    !desc3.equals("DONE.png")){
count++;
        }

       

if ((    !desc3.equals("DONE.png")) && (click3 == 1) && (count <=2) ) {




        if (temp.equals("0")) {
            card3Button.setIcon(a);
        } else if (temp.equals("1")) {
            card3Button.setIcon(b);
        } else if (temp.equals("2")) {
            card3Button.setIcon(c);
        } else if (temp.equals("3")) {
            card3Button.setIcon(d);
        } else if (temp.equals("4")) {
            card3Button.setIcon(e);
        } else if (temp.equals("5")) {
            card3Button.setIcon(f);
        } else if (temp.equals("6")) {
            card3Button.setIcon(g);
        } else if (temp.equals("7")) {
            card3Button.setIcon(h);
        }
//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[2] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[2] = 0;
        } }

    }//GEN-LAST:event_card3ButtonMouseClicked

    private void card4ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card4ButtonMouseClicked
        String temp = cards.get(3);
       String desc4 = ((ImageIcon)card4Button.getIcon()).getDescription();
        click4++;

                if (    !desc4.equals("DONE.png")){
count++;
        }

       

if ((    !desc4.equals("DONE.png")) && (click4 == 1) && (count <=2) ) {




        if (temp.equals("0")) {
            card4Button.setIcon(a);
        } else if (temp.equals("1")) {
            card4Button.setIcon(b);
        } else if (temp.equals("2")) {
            card4Button.setIcon(c);
        } else if (temp.equals("3")) {
            card4Button.setIcon(d);
        } else if (temp.equals("4")) {
            card4Button.setIcon(e);
        } else if (temp.equals("5")) {
            card4Button.setIcon(f);
        } else if (temp.equals("6")) {
            card4Button.setIcon(g);
        } else if (temp.equals("7")) {
            card4Button.setIcon(h);
        }


//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[3] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[3] = 0;
        }}
//        } else if (count > 2) {
//            card4Button.setIcon(back);
//        }

    }//GEN-LAST:event_card4ButtonMouseClicked

    private void card8ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card8ButtonMouseClicked
        String temp = cards.get(7);
               String desc8 = ((ImageIcon)card8Button.getIcon()).getDescription();
        click8++;

                if (    !desc8.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc8.equals("DONE.png")) && (click8 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card8Button.setIcon(a);
        } else if (temp.equals("1")) {
            card8Button.setIcon(b);
        } else if (temp.equals("2")) {
            card8Button.setIcon(c);
        } else if (temp.equals("3")) {
            card8Button.setIcon(d);
        } else if (temp.equals("4")) {
            card8Button.setIcon(e);
        } else if (temp.equals("5")) {
            card8Button.setIcon(f);
        } else if (temp.equals("6")) {
            card8Button.setIcon(g);
        } else if (temp.equals("7")) {
            card8Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[7] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[7] = 0;
        }}
//        } else if (count > 2) {
//            card8Button.setIcon(back);
//        }
    }//GEN-LAST:event_card8ButtonMouseClicked

    private void card5ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card5ButtonMouseClicked
        String temp = cards.get(4);
  String desc5 = ((ImageIcon)card5Button.getIcon()).getDescription();
        click5++;

                if (    !desc5.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc5.equals("DONE.png")) && (click5 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card5Button.setIcon(a);
        } else if (temp.equals("1")) {
            card5Button.setIcon(b);
        } else if (temp.equals("2")) {
            card5Button.setIcon(c);
        } else if (temp.equals("3")) {
            card5Button.setIcon(d);
        } else if (temp.equals("4")) {
            card5Button.setIcon(e);
        } else if (temp.equals("5")) {
            card5Button.setIcon(f);
        } else if (temp.equals("6")) {
            card5Button.setIcon(g);
        } else if (temp.equals("7")) {
            card5Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[4] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[4] = 0;
        }
//        } else if (count > 2) {
//            card5Button.setIcon(back);


        }    }//GEN-LAST:event_card5ButtonMouseClicked

    private void card6ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card6ButtonMouseClicked
        String temp = cards.get(5);
  String desc6 = ((ImageIcon)card6Button.getIcon()).getDescription();
        click6++;

                if (    !desc6.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc6.equals("DONE.png")) && (click6 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card6Button.setIcon(a);
        } else if (temp.equals("1")) {
            card6Button.setIcon(b);
        } else if (temp.equals("2")) {
            card6Button.setIcon(c);
        } else if (temp.equals("3")) {
            card6Button.setIcon(d);
        } else if (temp.equals("4")) {
            card6Button.setIcon(e);
        } else if (temp.equals("5")) {
            card6Button.setIcon(f);
        } else if (temp.equals("6")) {
            card6Button.setIcon(g);
        } else if (temp.equals("7")) {
            card6Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[5] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[5] = 0;
        
        }
        }

    }//GEN-LAST:event_card6ButtonMouseClicked

    private void card7ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card7ButtonMouseClicked
        String temp = cards.get(6);

          String desc7 = ((ImageIcon)card7Button.getIcon()).getDescription();
        click7++;

                if (    !desc7.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc7.equals("DONE.png")) && (click7 == 1) && (count <=2) ) {

        if (temp.equals("0")) {
            card7Button.setIcon(a);
        } else if (temp.equals("1")) {
            card7Button.setIcon(b);
        } else if (temp.equals("2")) {
            card7Button.setIcon(c);
        } else if (temp.equals("3")) {
            card7Button.setIcon(d);
        } else if (temp.equals("4")) {
            card7Button.setIcon(e);
        } else if (temp.equals("5")) {
            card7Button.setIcon(f);
        } else if (temp.equals("6")) {
            card7Button.setIcon(g);
        } else if (temp.equals("7")) {
            card7Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[6] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[6] = 0;
        } 
        }


    }//GEN-LAST:event_card7ButtonMouseClicked

    private void card9ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card9ButtonMouseClicked
        String temp = cards.get(8);

          String desc9 = ((ImageIcon)card9Button.getIcon()).getDescription();
        click9++;

                if (    !desc9.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc9.equals("DONE.png")) && (click9 == 1) && (count <=2) ) {

        if (temp.equals("0")) {
            card9Button.setIcon(a);
        } else if (temp.equals("1")) {
            card9Button.setIcon(b);
        } else if (temp.equals("2")) {
            card9Button.setIcon(c);
        } else if (temp.equals("3")) {
            card9Button.setIcon(d);
        } else if (temp.equals("4")) {
            card9Button.setIcon(e);
        } else if (temp.equals("5")) {
            card9Button.setIcon(f);
        } else if (temp.equals("6")) {
            card9Button.setIcon(g);
        } else if (temp.equals("7")) {
            card9Button.setIcon(h);
        }


//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[8] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[8] = 0;
        } 
        }
    }//GEN-LAST:event_card9ButtonMouseClicked

    private void card10ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card10ButtonMouseClicked
        String temp = cards.get(9);
  String desc10 = ((ImageIcon)card10Button.getIcon()).getDescription();
        click10++;

                if (    !desc10.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc10.equals("DONE.png")) && (click10 == 1) && (count <=2) ) {



        if (temp.equals("0")) {
            card10Button.setIcon(a);
        } else if (temp.equals("1")) {
            card10Button.setIcon(b);
        } else if (temp.equals("2")) {
            card10Button.setIcon(c);
        } else if (temp.equals("3")) {
            card10Button.setIcon(d);
        } else if (temp.equals("4")) {
            card10Button.setIcon(e);
        } else if (temp.equals("5")) {
            card10Button.setIcon(f);
        } else if (temp.equals("6")) {
            card10Button.setIcon(g);
        } else if (temp.equals("7")) {
            card10Button.setIcon(h);
        }
//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[9] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[9] = 0;
//        } else if (count > 2) {
//            card10Button.setIcon(back);
        }}


    }//GEN-LAST:event_card10ButtonMouseClicked

    private void card11ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card11ButtonMouseClicked
        String temp = cards.get(10);

          String desc11 = ((ImageIcon)card11Button.getIcon()).getDescription();
        click11++;

                if (    !desc11.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc11.equals("DONE.png")) && (click11 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card11Button.setIcon(a);
        } else if (temp.equals("1")) {
            card11Button.setIcon(b);
        } else if (temp.equals("2")) {
            card11Button.setIcon(c);
        } else if (temp.equals("3")) {
            card11Button.setIcon(d);
        } else if (temp.equals("4")) {
            card11Button.setIcon(e);
        } else if (temp.equals("5")) {
            card11Button.setIcon(f);
        } else if (temp.equals("6")) {
            card11Button.setIcon(g);
        } else if (temp.equals("7")) {
            card11Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[10] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[10] = 0;
//        } else if (count > 2) {
//            card11Button.setIcon(back);
        }}

    }//GEN-LAST:event_card11ButtonMouseClicked

    private void card12ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card12ButtonMouseClicked
        String temp = cards.get(11);
  String desc12 = ((ImageIcon)card12Button.getIcon()).getDescription();
        click12++;

                if (    !desc12.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc12.equals("DONE.png")) && (click12 == 1) && (count <=2) ) {

        if (temp.equals("0")) {
            card12Button.setIcon(a);
        } else if (temp.equals("1")) {
            card12Button.setIcon(b);
        } else if (temp.equals("2")) {
            card12Button.setIcon(c);
        } else if (temp.equals("3")) {
            card12Button.setIcon(d);
        } else if (temp.equals("4")) {
            card12Button.setIcon(e);
        } else if (temp.equals("5")) {
            card12Button.setIcon(f);
        } else if (temp.equals("6")) {
            card12Button.setIcon(g);
        } else if (temp.equals("7")) {
            card12Button.setIcon(h);
        }
//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[11] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[11] = 0;
//        } else if (count > 2) {
//            card12Button.setIcon(back);
        }}

    }//GEN-LAST:event_card12ButtonMouseClicked

    private void card13ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card13ButtonMouseClicked
        String temp = cards.get(12);

          String desc13 = ((ImageIcon)card13Button.getIcon()).getDescription();
        click13++;

                if (    !desc13.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc13.equals("DONE.png")) && (click13 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card13Button.setIcon(a);
        } else if (temp.equals("1")) {
            card13Button.setIcon(b);
        } else if (temp.equals("2")) {
            card13Button.setIcon(c);
        } else if (temp.equals("3")) {
            card13Button.setIcon(d);
        } else if (temp.equals("4")) {
            card13Button.setIcon(e);
        } else if (temp.equals("5")) {
            card13Button.setIcon(f);
        } else if (temp.equals("6")) {
            card13Button.setIcon(g);
        } else if (temp.equals("7")) {
            card13Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[12] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[12] = 0;
//        } else if (count > 2) {
//            card13Button.setIcon(back);
        }}

    }//GEN-LAST:event_card13ButtonMouseClicked

    private void card14ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card14ButtonMouseClicked
        String temp = cards.get(13);
  String desc14 = ((ImageIcon)card14Button.getIcon()).getDescription();

        click14++;
          if (    !desc14.equals("DONE.png")){
count++;
        }

//        count++;

if ((    !desc14.equals("DONE.png")) && (click14 == 1) && (count <=2) ) {



        if (temp.equals("0")) {
            card14Button.setIcon(a);
        } else if (temp.equals("1")) {
            card14Button.setIcon(b);
        } else if (temp.equals("2")) {
            card14Button.setIcon(c);
        } else if (temp.equals("3")) {
            card14Button.setIcon(d);
        } else if (temp.equals("4")) {
            card14Button.setIcon(e);
        } else if (temp.equals("5")) {
            card14Button.setIcon(f);
        } else if (temp.equals("6")) {
            card14Button.setIcon(g);
        } else if (temp.equals("7")) {
            card14Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[13] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[13] = 0;
//        } else if (count > 2) {
//            card14Button.setIcon(back);
        }}

    }//GEN-LAST:event_card14ButtonMouseClicked

    private void card15ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card15ButtonMouseClicked
        String temp = cards.get(14);

          String desc15 = ((ImageIcon)card15Button.getIcon()).getDescription();
        click15++;
                  if (    !desc15.equals("DONE.png")){
count++;
        }


//        count++;

if ((    !desc15.equals("DONE.png")) && (click15 == 1) && (count <=2) ) {


        if (temp.equals("0")) {
            card15Button.setIcon(a);
        } else if (temp.equals("1")) {
            card15Button.setIcon(b);
        } else if (temp.equals("2")) {
            card15Button.setIcon(c);
        } else if (temp.equals("3")) {
            card15Button.setIcon(d);
        } else if (temp.equals("4")) {
            card15Button.setIcon(e);
        } else if (temp.equals("5")) {
            card15Button.setIcon(f);
        } else if (temp.equals("6")) {
            card15Button.setIcon(g);
        } else if (temp.equals("7")) {
            card15Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[14] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[14] = 0;
//        } else if (count > 2) {
//            card15Button.setIcon(back);
        }}
    }//GEN-LAST:event_card15ButtonMouseClicked

    private void card16ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card16ButtonMouseClicked
        String temp = cards.get(15);
  String desc16 = ((ImageIcon)card16Button.getIcon()).getDescription();
        click16++;

                  if (    !desc16.equals("DONE.png")){
count++;
        }
//        count++;

if ((    !desc16.equals("DONE.png")) && (click16 == 1) && (count <=2) ) {



        if (temp.equals("0")) {
            card16Button.setIcon(a);
        } else if (temp.equals("1")) {
            card16Button.setIcon(b);
        } else if (temp.equals("2")) {
            card16Button.setIcon(c);
        } else if (temp.equals("3")) {
            card16Button.setIcon(d);
        } else if (temp.equals("4")) {
            card16Button.setIcon(e);
        } else if (temp.equals("5")) {
            card16Button.setIcon(f);
        } else if (temp.equals("6")) {
            card16Button.setIcon(g);
        } else if (temp.equals("7")) {
            card16Button.setIcon(h);
        }

//        count++;
        if (count == 1) {
            c1 = Integer.parseInt(temp);
            change[15] = 0;
        } else if (count == 2) {
            c2 = Integer.parseInt(temp);
            change[15] = 0;
//        } else if (count > 2) {
//            card16Button.setIcon(back);
//        }
        }}
    }//GEN-LAST:event_card16ButtonMouseClicked

    private void againButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againButtonActionPerformed
    click1 = 0;
    click2 = 0;
    click3 = 0;
    click4 = 0;
    click5 = 0;
    click6 = 0;
    click7 = 0;
    click8 = 0;
    click9 = 0;
    click10 = 0;
    click11 = 0;
    click12 = 0;
    click13 = 0;
    click14 = 0;
    click15 = 0;
    click16 = 0;
    click2 = 0;
    click2 = 0;
    click2 = 0;
    click2 = 0;
    click2 = 0;
        if (count != 0) {
          
            count = 0;
            if (c1 == c2) {
                  tries++;
                for (int y = 1; y <= 2; y++) {
                    if (change[0] == 0) {

                        change[0] = 2;
                        cardsLeft--;
//                    card1Button.setEnabled(false);
                        card1Button.setIcon(done);
                    } else if (change[1] == 0) {

                        change[1] = 2;
                        cardsLeft--;
//                    card2Button.setEnabled(false);
                        card2Button.setIcon(done);
                    } else if (change[2] == 0) {

                        change[2] = 2;
                        cardsLeft--;
//                    card3Button.setEnabled(false);
                        card3Button.setIcon(done);
                    } else if (change[3] == 0) {

                        change[3] = 2;
                        cardsLeft--;
//                    card4Button.setEnabled(false);
                        card4Button.setIcon(done);
                    } else if (change[4] == 0) {

                        change[4] = 2;
                        cardsLeft--;
//                    card5Button.setEnabled(false);
                        card5Button.setIcon(done);

                    } else if (change[5] == 0) {

                        change[5] = 2;
                        cardsLeft--;
//                    card6Button.setEnabled(false);
                        card6Button.setIcon(done);
                    } else if (change[6] == 0) {

                        change[6] = 2;
                        cardsLeft--;
//                    card7Button.setEnabled(false);
                        card7Button.setIcon(done);
                    } else if (change[7] == 0) {

                        change[7] = 2;
                        cardsLeft--;
//                    card8Button.setEnabled(false);
                        card8Button.setIcon(done);
                    } else if (change[8] == 0) {

                        change[8] = 2;
                        cardsLeft--;
//                    card9Button.setEnabled(false);
                        card9Button.setIcon(done);
                    } else if (change[9] == 0) {

                        change[9] = 2;
                        cardsLeft--;
//                    card10Button.setEnabled(false);
                        card10Button.setIcon(done);
                    } else if (change[10] == 0) {

                        change[10] = 2;
                        cardsLeft--;
//                    card11Button.setEnabled(false);
                        card11Button.setIcon(done);
                    } else if (change[11] == 0) {

                        change[11] = 2;
                        cardsLeft--;
//                    card12Button.setEnabled(false);
                        card12Button.setIcon(done);
                    } else if (change[12] == 0) {

                        change[12] = 2;
                        cardsLeft--;
//                    card13Button.setEnabled(false);
                        card13Button.setIcon(done);
                    } else if (change[13] == 0) {

                        change[13] = 2;
                        cardsLeft--;
//                    card14Button.setEnabled(false);
                        card14Button.setIcon(done);
                    } else if (change[14] == 0) {

                        change[14] = 2;
                        cardsLeft--;
//                    card15Button.setEnabled(false);
                        card15Button.setIcon(done);
                    } else if (change[15] == 0) {

                        change[15] = 2;
                        cardsLeft--;
//                    card16Button.setEnabled(false);
                        card16Button.setIcon(done);
                    }
                    if (cardsLeft == 0) {
                        cardsLeft = 16;
                        

                       JOptionPane.showMessageDialog(null, "CONGRATULATIONS!" + "\n" + "YOU WON in " + tries + " tries" + "\n" + "Fancy playing again? Just click Play! (Don't worry, we change the order of the cards:) )");
                       tries = 0;
                       winGif.setVisible(true);

                    }

                }


            } else {
tries++;
                for (int y = 1; y <= 2; y++) {

                    if (change[0] == 0) {
                        card1Button.setIcon(back);
                        change[0] = 1;
                    } else if (change[1] == 0) {
                        card2Button.setIcon(back);
                        change[1] = 1;
                    } else if (change[2] == 0) {
                        card3Button.setIcon(back);
                        change[2] = 1;
                    } else if (change[3] == 0) {
                        card4Button.setIcon(back);
                        change[3] = 1;
                    } else if (change[4] == 0) {
                        card5Button.setIcon(back);
                        change[4] = 1;
                    } else if (change[5] == 0) {
                        card6Button.setIcon(back);
                        change[5] = 1;
                    } else if (change[6] == 0) {
                        card7Button.setIcon(back);
                        change[6] = 1;
                    } else if (change[7] == 0) {
                        card8Button.setIcon(back);
                        change[7] = 1;
                    } else if (change[8] == 0) {
                        card9Button.setIcon(back);
                        change[8] = 1;
                    } else if (change[9] == 0) {
                        card10Button.setIcon(back);
                        change[9] = 1;
                    } else if (change[10] == 0) {
                        card11Button.setIcon(back);
                        change[10] = 1;
                    } else if (change[11] == 0) {
                        card12Button.setIcon(back);
                        change[11] = 1;
                    } else if (change[12] == 0) {
                        card13Button.setIcon(back);
                        change[12] = 1;
                    } else if (change[13] == 0) {
                        card14Button.setIcon(back);
                        change[13] = 1;
                    } else if (change[14] == 0) {
                        card15Button.setIcon(back);
                        change[14] = 1;
                    } else if (change[15] == 0) {
                        card16Button.setIcon(back);
                        change[15] = 1;
                    }
                }
            }
        }









//continue to Card 16
    }//GEN-LAST:event_againButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MemoryUI().setVisible(true);
                JOptionPane.showMessageDialog(null, "HELLO! Press Play to start the game and learn how to play!");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane Rules;
    private javax.swing.JButton againButton;
    private javax.swing.JLabel backgroundLogo;
    private javax.swing.JButton card10Button;
    private javax.swing.JButton card11Button;
    private javax.swing.JButton card12Button;
    private javax.swing.JButton card13Button;
    private javax.swing.JButton card14Button;
    private javax.swing.JButton card15Button;
    private javax.swing.JButton card16Button;
    private javax.swing.JButton card1Button;
    private javax.swing.JButton card2Button;
    private javax.swing.JButton card3Button;
    private javax.swing.JButton card4Button;
    private javax.swing.JButton card5Button;
    private javax.swing.JButton card6Button;
    private javax.swing.JButton card7Button;
    private javax.swing.JButton card8Button;
    private javax.swing.JButton card9Button;
    private javax.swing.JButton exitButton;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel winGif;
    // End of variables declaration//GEN-END:variables
}
